### ISSUE TITLE
Remove empty columns at end of CSV rows

### ISSUE THREAD

**Issue by helrond** [RepoData/RepoData#15]
`data.csv` has empty columns at the end of each row, and should be trimmed so that "notes" is the last column.

**Comment by tanseyem** [comment]
are you still working on this? I was thinking about running the data through ArcMap again to geocode it before our next RepoData meeting, but don't want to do it until you're done with whatever round of work you're doing.

**Comment by helrond** [comment]
I think you can go ahead and do the geocoding. Now that we have ids it will be possible to work on different tracks.
