### ISSUE TITLE
Improve datatypes in JSON file

### ISSUE THREAD

**Issue by helrond** [RepoData/RepoData#18]
Currently, everything in the JSON file is encoded as a string. However, some of the values are actually floats and integers. This is related to #16 

@edsu do you have any tips on how to approach this?

**Comment by edsu** [comment]
How about we start by documenting what the types should be, then we can go about making sure they are maintained? Does this look good?

| Name                             | Type     |
| -------------------------------- | -------- |
| id                               | string   |
| repository_name_unauthorized     | string   |
| name_notes                       | string   |
| parent_org_unauthorized          | string   |
| repository_name_authorized       | string   |
| repository_identifier_authorized | string   |
| repository_type                  | string   |
| location_type                    | string   |
| street_address_1                 | string   |
| street_address_2                 | string   |
| st_city                          | string   |
| st_zip_code_5_numbers            | integer  |
| st_zip_code_4_following_numbers  | integer  |
| street_address_county            | string   |
| state                            | string   |
| url                              | string   |
| latitude                         | float    |
| longitude                        | float    |
| language_of_entry                | string   |
| date_entry_recorded              | datetime |
| entry_recorded_by                | datetime |
| source_of_repository_data        | string   |
| url_of_source_of_repository_data | string   |
| notes                            | string   |
| geocode_confidence               | float    |

**Comment by helrond** [comment]
@edsu this all looks right to me. Looks like dates are YYYY-MM-DD now, so we should be in good shape to parse.
