### ISSUE TITLE
Consolidate “Tribal”/“Tribal Archives” and “Religious”/“Religious Archives”

### ISSUE THREAD

**Issue by helrond** [RepoData/RepoData#24]
**Describe the bug**
The source data file currently contains both “Tribal” and “Tribal Archives” and “Religious” and “Religious Archives”. 

**Expected behavior**
These should be consolidated into simply “Tribal” and “Religious”.

**Comment by edsu** [comment]
It looks like `Tribal Archives` and `Religious Archives` are used in the `repository_type` column?
