### ISSUE TITLE
Implement automated tests

### ISSUE THREAD

**Issue by helrond** [RepoData/RepoData#30]
**Is your feature request related to a problem? Please describe.**
It would be great if there were some automated tests which gave us some confidence that pull requests with new data are correctly structured, and that derivatives have been generated as expected.

**Describe the solution you'd like**
Some tests which can be run in an automated pipeline (like Travis CI or GitHub Actions). We have some utilities already in place for this which could be rewritten as tests. Additionally, utilities such as `convert.py` could be run and then the diff could be checked to make sure that the derivates were created as expected.

**Comment by edsu** [comment]
New automated tests were added in #35!
