### ISSUE TITLE
Identifiers for repositories

### ISSUE THREAD

**Issue by helrond** [RepoData/RepoData#4]
For a variety of reasons, it would be really great if each repository had an identifier recorded in the data. I see there is a column for an authorized identifier, but I'm wondering if we also need some sort of local identifier? This would help us manage the data over time, and also provide consistent access to it over the web (via a website, etc).

**Comment by tanseyem** [comment]
Yeah, we definitely talked about using MARC Organization Codes when possible (https://www.loc.gov/marc/organizations/) but clearly that would be an issue with small community historical societies that are basically outside the grid. Do you have a recommendation for creating a local identifier structure? 

I would love to reference some kind of existing geospatial identifiers like Census tract numbers, but it occurs to me that doing something that ambitious might be better saved for one of my sabbatical projects later this year, and we may just need a local identifier system in the meantime.

**Comment by helrond** [comment]
Cool - I think there's space for multiple identifiers; what we need right now is just something that uniquely identifies each row in the data. 

There are a number of ways of creating unique identifiers, but I've generally used the `uuid` Python library, which generates UUIDs which look like `a8098c1a-f86e-11da-bd1a-00112444be1e`. @edsu do you have other suggestions here?

**Comment by tingletech** [comment]
ARK's from SNAC for the EAC-CPF record for the repository?

**Comment by edsu** [comment]
I'm skeptical that SNAC will have identifiers for all of the repositories in RepoData, and even if it did there would be significant matching work to do to connect them?

I do like the idea of potentially creating ARK identifiers for these, which could incorporate a uuid like @helrond mentioned. I believe it's fairly painless to register a [NAAN](https://n2t.net/e/pub/naan_table.html) but the question would be what organization should be used? Would it be presumptuous to make it SAA?

**Comment by tingletech** [comment]
From what I understand, SNAC has created or intends to create EAC-CPF records for all the archives that are represented in SNAC.  They also want the latitude and longitude information.

"Ultimately we would like to ensure that someone takes over long-term stewardship of the RepoData data set" [Completing RepoData (for now)](https://repositorydata.wordpress.com/2019/06/14/completing-repodata-for-now/).  SNAC might be a good home for this data.

uuids seem sort of long and unwieldy considering the size of universe of things getting identifiers.    Maybe consider something like https://hashids.org ?

**Comment by tanseyem** [comment]
> "Ultimately we would like to ensure that someone takes over long-term stewardship of the RepoData data set" [Completing RepoData (for now)](https://repositorydata.wordpress.com/2019/06/14/completing-repodata-for-now/). SNAC might be a good home for this data.

RepoData has thousands of repositories represented that have no networked archival description whatsoever (we're talking small neighborhood historical societies with, at best, a Facebook page. They don't have online finding aids, let alone EAD-encoded finding aids). My impression has been that SNAC has been very focused on elite research institutions active in networked archival description, so I am very curious whether SNAC is a realistic entity for taking this on.

**Comment by tanseyem** [comment]
Who's going to be at SAA? Some of these conversations are a bit over my head, but I'd like to learn more about this. And while certainly this is open data and Ben and I are not territorial about it, I do also feel like I want to make sure whatever is happening with it is consistent with the original intent and values with which we built up this project.

**Comment by bmrgoldman** [comment]
Grateful for everyone's ideas here, and sorry to jump in so late. I'd advocate for Hillel's original proposal, which would create an internally consistent method to (presumably) disambiguate these lines of data to support some immediate future work. It would be nice to build on some of these other initiatives, but they do seem like they'll require further evaluation. And as Hillel indicated, a uuid approach doesn't preclude these other options down the line.

**Comment by helrond** [comment]
I am _not_ going to be at SAA this year, unfortunately. 

There are definitely some bigger questions to be worked through here, but it sounds like there's a consensus on adding local identifiers to the data first, and then dealing with those larger questions at a later date. I think @tingletech is right - truly unique UUIDs seem like overkill in this context, so I'll look at hashids and potentially [Nano IDs](https://zelark.github.io/nano-id-cc/)

**Comment by edsu** [comment]
If the idea was to have something a bit more legible and shorter we could generate them using a little reciple like:

    {2-char-state-abbr}{city-initial-char}{org-name-initial-char}{sequence-id}

So 

    Ilanka Cultural Center
    Cordova, AK

Would be:

    akci0

We would need a little program to take a pass through the data and keep track if the sequence id needed to be incremented. But then when new repos are added you could simply scan the table to see if had been used already, and increment as needed? 

s that a crazy idea?

so like saamd1

**Comment by edsu** [comment]
... and thanks to @tanseyem for the prompt to go read the history of the MARC org codes :-) http://www.loc.gov/marc/organizations/

**Comment by helrond** [comment]
@edsu I don't think that's a crazy idea (although the archivist in me gets twitchy every time someone starts talking about embedding semantics in identifiers). I can see if I can work up something using this approach.

**Comment by edsu** [comment]
Yes, I hear you about the semantics. I'm happy to help too if you want.

**Comment by helrond** [comment]
@edsu it's probably going to take me a couple of weeks to get to this so if you have immediate capacity, have at it!

**Comment by tingletech** [comment]
re: the id proposal above -- what would happen when an archive moves to a different city?  I think we have had this happen at least once for OAC.

**Comment by edsu** [comment]
I think identifiers should be persistent. So as long as it is the same organization it should keep the identifier? The heuristic is just to derive a unique identifier, so honestly it could just be a number as well.

**Comment by helrond** [comment]
Fixed by #12
