### ISSUE TITLE
Remove state spreadsheets (excel folder)

### ISSUE THREAD

**Issue by tanseyem** [RepoData/RepoData#8]
I have created a copy of the state spreadsheets should anyone need to view them in the future on the OSF documentation page for the larger RepoData project (https://osf.io/cft8r/). Suggest removing them from the github repo in order to make maintenance of the master set of data easier.

**Comment by edsu** [comment]
I'm glad you all decided to move away from storing the canonical data in Excel! Of course people will still be able to edit them in Excel by importing the CSV. There will just be the extra step of exporting to CSV when saving. The first time we should probably double check that Excel doesn't mangle any of the data during import/export though.
